/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PopWindow: typeof import('./src/components/pop-window.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCollapse: typeof import('@varlet/ui')['_CollapseComponent']
    VarCollapseItem: typeof import('@varlet/ui')['_CollapseItemComponent']
    VarCollapseTransition: typeof import('@varlet/ui')['_CollapseTransitionComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarDrag: typeof import('@varlet/ui')['_DragComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
