/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiButton: typeof import('./src/components/ai-button.vue')['default']
    PopWindow: typeof import('./src/components/pop-window.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Te: typeof import('./src/components/te.vue')['default']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBackTop: typeof import('@varlet/ui')['_BackTopComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCollapse: typeof import('@varlet/ui')['_CollapseComponent']
    VarCollapseItem: typeof import('@varlet/ui')['_CollapseItemComponent']
    VarCollapseTransition: typeof import('@varlet/ui')['_CollapseTransitionComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarDrag: typeof import('@varlet/ui')['_DragComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarList: typeof import('@varlet/ui')['_ListComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarMenuOption: typeof import('@varlet/ui')['_MenuOptionComponent']
    VarMenuSelect: typeof import('@varlet/ui')['_MenuSelectComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTimePicker: typeof import('@varlet/ui')['_TimePickerComponent']
    ZForm: typeof import('./src/components/z-form.vue')['default']
    ZFormItem: typeof import('./src/components/z-form-item.vue')['default']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
