/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/Announcement.vue')['default']
    BarCharts: typeof import('./src/components/BarCharts.vue')['default']
    Draw: typeof import('./src/components/Draw.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfinteList: typeof import('./src/components/InfinteList.vue')['default']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    LineCharts: typeof import('./src/components/LineCharts.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalExample: typeof import('./src/components/ModalExample.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./src/components/Share.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TableRows: typeof import('./src/components/TableRows.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    ToTop: typeof import('./src/components/ToTop.vue')['default']
  }
}
